import type { PermissionRule } from "./types"

export const BUILTIN_RULES: PermissionRule[] = [
  { tool: "Bash", action: "ask", matches: { command: "*git*push*" } },
  { tool: "Bash", action: "ask", matches: { command: "*git*force*" } },
  { tool: "Bash", action: "ask", matches: { command: "*rm*-rf*" } },
  { tool: "Bash", action: "ask", matches: { command: "*sudo*" } },

  { tool: "Bash", action: "allow", matches: { command: "ls" } },
  { tool: "Bash", action: "allow", matches: { command: "ls *" } },
  { tool: "Bash", action: "allow", matches: { command: "cat *" } },
  { tool: "Bash", action: "allow", matches: { command: "head *" } },
  { tool: "Bash", action: "allow", matches: { command: "tail *" } },
  { tool: "Bash", action: "allow", matches: { command: "grep *" } },
  { tool: "Bash", action: "allow", matches: { command: "find *" } },
  { tool: "Bash", action: "allow", matches: { command: "wc *" } },
  { tool: "Bash", action: "allow", matches: { command: "pwd" } },
  { tool: "Bash", action: "allow", matches: { command: "which *" } },
  { tool: "Bash", action: "allow", matches: { command: "echo *" } },

  { tool: "Bash", action: "allow", matches: { command: "npm run *" } },
  { tool: "Bash", action: "allow", matches: { command: "npm test*" } },
  { tool: "Bash", action: "allow", matches: { command: "npm install*" } },
  { tool: "Bash", action: "allow", matches: { command: "yarn *" } },
  { tool: "Bash", action: "allow", matches: { command: "pnpm *" } },
  { tool: "Bash", action: "allow", matches: { command: "bun *" } },
  { tool: "Bash", action: "allow", matches: { command: "bun run *" } },
  { tool: "Bash", action: "allow", matches: { command: "bun test*" } },
  { tool: "Bash", action: "allow", matches: { command: "bun install*" } },

  { tool: "Bash", action: "allow", matches: { command: "go build*" } },
  { tool: "Bash", action: "allow", matches: { command: "go test*" } },
  { tool: "Bash", action: "allow", matches: { command: "go run*" } },
  { tool: "Bash", action: "allow", matches: { command: "cargo build*" } },
  { tool: "Bash", action: "allow", matches: { command: "cargo test*" } },
  { tool: "Bash", action: "allow", matches: { command: "cargo run*" } },
  { tool: "Bash", action: "allow", matches: { command: "python *" } },
  { tool: "Bash", action: "allow", matches: { command: "python3 *" } },
  { tool: "Bash", action: "allow", matches: { command: "pip install*" } },
  { tool: "Bash", action: "allow", matches: { command: "pip3 install*" } },

  { tool: "Bash", action: "allow", matches: { command: "git status*" } },
  { tool: "Bash", action: "allow", matches: { command: "git log*" } },
  { tool: "Bash", action: "allow", matches: { command: "git diff*" } },
  { tool: "Bash", action: "allow", matches: { command: "git show*" } },
  { tool: "Bash", action: "allow", matches: { command: "git branch*" } },
  { tool: "Bash", action: "allow", matches: { command: "git checkout*" } },
  { tool: "Bash", action: "allow", matches: { command: "git add*" } },
  { tool: "Bash", action: "allow", matches: { command: "git commit*" } },
  { tool: "Bash", action: "allow", matches: { command: "git pull*" } },
  { tool: "Bash", action: "allow", matches: { command: "git fetch*" } },
  { tool: "Bash", action: "allow", matches: { command: "git stash*" } },
  { tool: "Bash", action: "allow", matches: { command: "git clone*" } },

  { tool: "Bash", action: "allow", matches: { command: "mkdir *" } },
  { tool: "Bash", action: "allow", matches: { command: "touch *" } },
  { tool: "Bash", action: "allow", matches: { command: "cp *" } },
  { tool: "Bash", action: "allow", matches: { command: "mv *" } },

  { tool: "Read", action: "allow" },
  { tool: "Edit", action: "allow" },
  { tool: "Write", action: "allow" },
  { tool: "Delete", action: "ask" },
  { tool: "Grep", action: "allow" },
  { tool: "Glob", action: "allow" },
  { tool: "Task", action: "allow" },
  { tool: "Finder", action: "allow" },
  { tool: "Oracle", action: "allow" },
  { tool: "Painter", action: "allow" },
  { tool: "Librarian", action: "allow" },
  { tool: "Kraken", action: "allow" },
  { tool: "TodoWrite", action: "allow" },
  { tool: "TodoRead", action: "allow" },
  { tool: "WebFetch", action: "allow" },
  { tool: "ReadPlan", action: "allow" },
  { tool: "EditPlan", action: "allow" },
  { tool: "ReadArtifact", action: "allow" },
  { tool: "EditArtifact", action: "allow" },
  { tool: "LookAt", action: "allow" },
  { tool: "Mermaid", action: "allow" },
  { tool: "ReadGitHubFile", action: "allow" },
  { tool: "SearchGitHubCode", action: "allow" },
  { tool: "SearchGitHubCommits", action: "allow" },
  { tool: "GetGitHubDiff", action: "allow" },
  { tool: "FindGitHubFiles", action: "allow" },
  { tool: "WebSearch", action: "allow" },
  { tool: "ReadThread", action: "allow" },

  { tool: "Bash", action: "ask" },
]
